//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Framework.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS.Framework.Resource.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 10.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters10 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 100.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters100 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 100.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters1000 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 150.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters150 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 2.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters2 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 20.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters20 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 2000.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters2000 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 3.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters3 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 5.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters5 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 50.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters50 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 500.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters500 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters500", resourceCulture);
            }
        }
    }
}
