//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Resource.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChurchResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChurchResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS.Resource.Registration.ChurchResource", typeof(ChurchResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igreja.
        /// </summary>
        public static string Church {
            get {
                return ResourceManager.GetString("Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sigla é obrigatório..
        /// </summary>
        public static string InitialsIsRequired {
            get {
                return ResourceManager.GetString("InitialsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova igreja.
        /// </summary>
        public static string NewChurch {
            get {
                return ResourceManager.GetString("NewChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone é obrigatório..
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome é obrigatório..
        /// </summary>
        public static string TheNameIsRequired {
            get {
                return ResourceManager.GetString("TheNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 10.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters10 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o tamanho máximo de caracteres: 150.
        /// </summary>
        public static string YouHaveReachedTheSizeMaximumCharacters150 {
            get {
                return ResourceManager.GetString("YouHaveReachedTheSizeMaximumCharacters150", resourceCulture);
            }
        }
    }
}
