// <auto-generated />
namespace EMS.Data.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0016));
        
        string IMigrationMetadata.Id
        {
            get { return "201608212210120_001-6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
